[tools]
dotnet = "latest"
k9s = "latest"
node = "23.6.0"
python = "latest"
ruby = "latest"
shellcheck = "latest"
trivy = "latest"
uv = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
